sudo: required

language: generic

services:
  - docker

before_install:
  - cp .env.example .env
  - ./develop artisan key:generate
  - ./develop up -d
  - ./develop composer install

script:
  - ./develop phpunit