version: '2'
services:
  app:
    image: invokedigital/laravel:latest
    volumes:
     - .:/var/www/html
    networks:
     - app-net
  node:
    image: node:9
    working_dir: /app
    container_name: vue-docker
    volumes:
     - .:/app
    networks:
     - app-net
  mysql:
    image: mysql:5.7
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - app-net
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - app-net